name: CI

on:
  push:
    branches:
      - master

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: [ 16, 18, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js | ${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
          
      - name: Generate tag
        id: generate_tag
        run: | 
         SHA=$(echo $GITHUB_SHA | head -c7)
         echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: docker build -t wired:${{steps.generate_tag.outputs.sha}} .